### ISSUE TITLE
burnAngle

### ISSUE THREAD

**Issue by L-t-p** [Seeed-Studio/Seeed_Arduino_AS5600#22]
Hi
For Angle programming, I set the minimum value (36 degrees) and maximum value (180 degrees) and solidified into the chip, but I read the scaled Angle value between 0 and 144 degrees.
Looking forward to your reply.
![image](https://user-images.githubusercontent.com/100546252/174594363-98d6a73b-6d39-4c56-adbc-967c6d895e3a.png)

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

Do you still have this problem now?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
