### ISSUE TITLE
Wrong information

### ISSUE THREAD

**Issue by Steve102420** [Seeed-Studio/Seeed_Arduino_AS5600#28]
Sorry if I misunderstood something, but I think you wrote the description about the 3.3V power supply wrong.
According to the datasheet, if the 5V and 3.3V inputs are connected, the maximum input voltage will be 3.3V.
If you remove the 0 ohm resistor, the sensor can be used from 5V to 3.3V.

![image](https://user-images.githubusercontent.com/62448442/215184405-40301e0a-8d49-4182-beec-fca2dce43f9d.png)

**Comment by Lesords** [comment]
Hello,

I'm very sorry to have kept you waiting so long.

It seems to be a translation problem, I have corrected it.

But your last sentence may be a bit wrong, after removing it, it is 5v.

**Comment by Lesords** [comment]
I'm going to close this issue, feel free to re-open it if you have any other questions.
